/**
 * Copyright (c) 2026, WSO2 LLC. (https://www.wso2.com).
 *
 * WSO2 LLC. licenses this file to you under the Apache License,
 * Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

-- TOPIC definition
CREATE TABLE IF NOT EXISTS TOPIC (
  TOPIC_ID VARCHAR(64) NOT NULL,
  ORG_ID VARCHAR(128) NOT NULL,
  NAME VARCHAR(225) NOT NULL,
  DESCRIPTION VARCHAR(255) DEFAULT NULL,
  STATUS VARCHAR(32) DEFAULT 'ACTIVE' NOT NULL,
  PRIMARY KEY (TOPIC_ID),
  CONSTRAINT UQ_TOPIC_ORG_NAME UNIQUE (ORG_ID, NAME)
);

-- EVENT definition
CREATE TABLE IF NOT EXISTS EVENT (
  EVENT_ID VARCHAR(64) NOT NULL,
  ORG_ID VARCHAR(128) NOT NULL,
  GROUP_ID VARCHAR(128) NOT NULL,
  TOPIC_ID VARCHAR(64) NOT NULL,
  PAYLOAD CLOB NOT NULL,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  PRIMARY KEY (EVENT_ID),
  CONSTRAINT FK_E_TOPIC FOREIGN KEY (TOPIC_ID) REFERENCES TOPIC (TOPIC_ID)
);

-- EVENT_PURPOSE definition
CREATE TABLE IF NOT EXISTS EVENT_PURPOSE (
  EVENT_ID VARCHAR(64) NOT NULL,
  PURPOSE_NAME VARCHAR(128) NOT NULL,
  PRIMARY KEY (EVENT_ID, PURPOSE_NAME),
  CONSTRAINT FK_EVENT_PURPOSES_EVENT FOREIGN KEY (EVENT_ID) REFERENCES EVENT (EVENT_ID) ON DELETE CASCADE
);

-- SUBSCRIPTION definition
CREATE TABLE IF NOT EXISTS SUBSCRIPTION (
  SUBSCRIPTION_ID VARCHAR(64) NOT NULL,
  ORG_ID VARCHAR(128) NOT NULL,
  GROUP_ID VARCHAR(128) NOT NULL,
  TOPIC_ID VARCHAR(64) NOT NULL,
  STATUS VARCHAR(32) DEFAULT 'ACTIVE' NOT NULL,
  PURPOSE_FILTER_MODE VARCHAR(32) NOT NULL,
  CALLBACK_URL VARCHAR(512) DEFAULT NULL,
  SHARED_SECRET VARCHAR(512) DEFAULT NULL,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  DELIVERY_MODE VARCHAR(32) NOT NULL,
  PRIMARY KEY (SUBSCRIPTION_ID),
  CONSTRAINT FK_S_TOPIC FOREIGN KEY (TOPIC_ID) REFERENCES TOPIC (TOPIC_ID),
  -- Prevents duplicate non-deleted subscriptions for the same org/group/topic/filter combination.
  -- The application-layer duplicate check (SELECT then INSERT) has a TOCTOU race at high concurrency;
  -- this constraint is the last line of defence and causes the DB to reject the second INSERT atomically.
  CONSTRAINT UQ_SUBSCRIPTION_ACTIVE UNIQUE (ORG_ID, GROUP_ID, TOPIC_ID, PURPOSE_FILTER_MODE, STATUS)
);

-- SUBSCRIPTION_PURPOSE definition
CREATE TABLE IF NOT EXISTS SUBSCRIPTION_PURPOSE (
  SUBSCRIPTION_ID VARCHAR(64) NOT NULL,
  PURPOSE_NAME VARCHAR(128) NOT NULL,
  PRIMARY KEY (SUBSCRIPTION_ID, PURPOSE_NAME),
  CONSTRAINT FK_SUBSCRIPTION_PURPOSES_SUBSCRIPTION FOREIGN KEY (SUBSCRIPTION_ID) REFERENCES SUBSCRIPTION (SUBSCRIPTION_ID) ON DELETE CASCADE
);

-- WEBHOOK_DELIVERY definition
CREATE TABLE IF NOT EXISTS WEBHOOK_DELIVERY (
  DELIVERY_ID VARCHAR(64) NOT NULL,
  SUBSCRIPTION_ID VARCHAR(64) NOT NULL,
  EVENT_ID VARCHAR(64) NOT NULL,
  STATUS VARCHAR(32) DEFAULT 'PENDING' NOT NULL,
  ATTEMPT_COUNT INT DEFAULT 0 NOT NULL,
  NEXT_RETRY_AT TIMESTAMP NULL DEFAULT NULL,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  DELIVERED_AT TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (DELIVERY_ID)
);

-- WEBHOOK_DELIVERY_ACK definition
CREATE TABLE IF NOT EXISTS WEBHOOK_DELIVERY_ACK (
  ACK_ID VARCHAR(64) NOT NULL,
  DELIVERY_ID VARCHAR(64) NOT NULL,
  STATUS VARCHAR(32) NOT NULL,
  RECEIVED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  PRIMARY KEY (ACK_ID)
);

-- WEBHOOK_DELIVERY_AUDIT definition
CREATE TABLE IF NOT EXISTS WEBHOOK_DELIVERY_AUDIT (
  AUDIT_ID VARCHAR(64) NOT NULL,
  DELIVERY_ID VARCHAR(64) NOT NULL,
  ATTEMPT_NUMBER INT NOT NULL,
  RESPONSE_STATUS_CODE INT DEFAULT NULL,
  ERROR_MESSAGE VARCHAR(512) DEFAULT NULL,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  PRIMARY KEY (AUDIT_ID)
);

-- POLL_DELIVERY definition
CREATE TABLE IF NOT EXISTS POLL_DELIVERY (
  DELIVERY_ID VARCHAR(64) NOT NULL,
  SUBSCRIPTION_ID VARCHAR(64) NOT NULL,
  EVENT_ID VARCHAR(64) NOT NULL,
  STATUS VARCHAR(32) DEFAULT 'PENDING' NOT NULL,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  PRIMARY KEY (DELIVERY_ID)
);
